### ISSUE TITLE
GetLocation and ListLocations RPCs not present in Dialogflow CX library

### ISSUE THREAD

**Issue by matthewayne** [googleapis/python-dialogflow-cx#248]
#### Steps to reproduce

  1. Install the Dialogflow CX Python library: `pip install google-cloud-dialogflow-cx`
  2. Attempt to use the document `google.cloud.locations` interface as documented on cloud.google.com: https://cloud.google.com/dialogflow/cx/docs/reference/rpc/google.cloud.location#google.cloud.location.Locations.ListLocations

#### Expected result
a `google.cloud.location` interface to be present in the Dialogflow library

#### Actual result
No `google.cloud.location` interface and no way to call GetLocation or ListLocation RPCs despite them being documented.

#### Code example

```python
import google.cloud.location
```

#### Stack trace
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'google.cloud.location'
```

**Comment by galz10** [comment]
Hey Matt, have you tried [list_location](https://googleapis.dev/python/dialogflow-cx/latest/dialogflowcx_v3beta1/agents.html?highlight=listlocation) and [get_location](https://googleapis.dev/python/dialogflow-cx/latest/dialogflowcx_v3beta1/agents.html?highlight=listlocation)

**Comment by matthewayne** [comment]
Those methods work as described in the docs you link but the official documentation on cloud.google.com indicates that a `google.cloud.location` interface should exist: https://cloud.google.com/dialogflow/cx/docs/reference/rpc/google.cloud.location#google.cloud.location.Locations.ListLocations

Is there something we can do to make sure the documentation and library are consistent?

**Comment by galz10** [comment]
The documentation you linked is for the REST API, and i believe these functions are available in the rest API.
