### ISSUE TITLE
CRUD Flows

### ISSUE THREAD

**Issue by loriecastillano** [googleapis/python-dialogflow-cx#46]
Hello good day!

I think an examples for CRUD of Flows/Page would be great! I am kinda lost with creating the request object. Thanks in advance!

**Comment by munkhuushmgl** [comment]
@wuyuexin Will this be supported in the future some time?

**Comment by munkhuushmgl** [comment]
@loriecastillano I am working on logging a bug internally.

I do not have ETA for this feature request. However, I will update this issue once feature request is updated.

**Comment by kmaphoenix** [comment]
Hi @loriecastillano !

We just open sourced a new high level scripting library on GCP that extends this base library.  
The Dialogflow CX Scripting API, or SCRAPI for short, is meant as a simple high level API to perform common bot building and maintenance tasks.

You can find it here:  
https://github.com/GoogleCloudPlatform/dfcx-scrapi

Check out the `examples` folder for ways to utilize the library to perform CRUD functions that you're looking for.  
For a really fast quick start, try out one of the Jupyter Notebooks by importing it directly into Google Colab, like this [Bot Building 101 notebook](https://github.com/GoogleCloudPlatform/dfcx-scrapi/blob/main/examples/bot_building_101.ipynb).

**Comment by matthewayne** [comment]
Closing for now, please reopen if the above @kmaphoenix's comment didn't answer your quesiton!
