### ISSUE TITLE
Sample test failure: webhook_prebuilt_telecom.py ValueError: month must be in 1..12

### ISSUE THREAD

**Issue by nicain** [googleapis/python-dialogflow-cx#478]
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-dialogflow-cx%2Fsamples%2Fpython3.10%2Fperiodic

**Comment by parthea** [comment]
Fixed in https://github.com/googleapis/python-dialogflow-cx/pull/479
